apiVersion: v1
kind: Service
metadata:
  name: retail-onboarding
  namespace: retail
spec:
  selector:
    app: retail-onboarding
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 31678
  type: NodePort