name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.GIT_USERNAME }}
        password: ${{ env.GIT_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: kaributechworkflows/retail-onboarding:${{ github.sha }}
        
    - name: Update deployment image
      run: |
        export IMAGE_TAG="${{ github.sha }}"
        envsubst < ./charts/deployment.yaml > ./charts/final-deployment.yaml
        
    - name: Deploy to Kubernetes
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f ./charts/final-deployment.yaml